### ISSUE TITLE
'certman' leads to "ImportError: No module named terminaltables"

### ISSUE THREAD

**Issue by vanger-cat** [mbs-dev/certman#1]
Получил вот такую ошибку инструкции из README.md:

```
(env)Vangers-MBP:certman vanger$ certman
Traceback (most recent call last):
  File "/Users/vanger/Documents/MBS/BuildStore/certman/env/bin/certman", line 4, in <module>
    from certman.manager import Manager
  File "/Users/vanger/Documents/MBS/BuildStore/certman/env/lib/python2.7/site-packages/certman/manager.py", line 7, in <module>
    from terminaltables import AsciiTable
ImportError: No module named terminaltables
```

Может дело в том, что я сделал pip install в virtualenv?  Просто не хотел ставить его себе в глобальное окружение...

**Comment by vladignatyev** [comment]
@vanger-cat use it with global environment. `terminaltables` doesn't work inside `virtualenv`, but it's _must_ thing bringing up all CLI UI of the app.

**Comment by vanger-cat** [comment]
@vladignatyev Tried to use it inside global environment. Result is the following:

```
Vangers-MBP:~ vanger$ certman
Traceback (most recent call last):
  File "/usr/local/bin/certman", line 4, in <module>
    from certman.manager import Manager
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/certman/manager.py", line 7, in <module>
    from terminaltables import AsciiTable
ImportError: No module named terminaltables
```

**Comment by vanger-cat** [comment]
Fixed with commit https://github.com/mbs-dev/certman/commit/7e46af3115e4278fa4bd56c683e4ccfd25e04695
